### PR TITLE
Add support for Laravel 8

### PR DESCRIPTION
**Pull request by SamuelNitsche**
This PR adds support for Laravel 8 which is going to be released on September 8th. This PR is based on the latest laravel 8 development version which should not change very much until its release.

### CODE REVIEW

**Comment by Xinecraft** [comment]
Is this project no longer under development? @clarkeash

**Comment by dom235** [comment]
hugs and kisses 😚 we also need this merge

**Comment by clarkeash** [comment]
Sorry not had a chance to get to this, I will take a look the weekend.

**Comment by dom235** [comment]
Super awesome bro 💖 thanks in advance!

**Comment by clarkeash** [comment]
@SamuelNitsche thanks for the work on this.
@schranzer235 @kinnngg v6 has just been tagged!

**Pull request merged**
