### PR TITLE
Add Spanish translations

### PR DESCRIPTION
**Pull request by m1guelpf**

### CODE REVIEW

**Comment by m1guelpf** [comment]
@clarkeash What do you think?

**Comment by clarkeash** [comment]
I am in 2 minds about this:

I think it would be really cool to have other languages supported out of the box, however I have no way of knowing what the translation actually says, and if I add a message in the future the Spanish translation then becomes out of date.

Even with this said, I am tempted to merge.

**Comment by m1guelpf** [comment]
@clarkeash It's always better to have an outdated translation than not havin anything. Also, I can mantain it if you ping me every time you add a new message.

**Comment by clarkeash** [comment]
Ill merge it and we can see how it goes.

**Pull request merged**
