### PR TITLE
Add Cleanup Command

### LINKED ISSUE #10: Cleanup Command
Add an artisan command to remove expired invites from the database. I can do it if you want.

### PR DESCRIPTION
**Pull request by m1guelpf**
Fix #10

### CODE REVIEW

**Comment by clarkeash** [comment]
Are you able to add some tests?

**Comment by m1guelpf** [comment]
@clarkeash I will add them when I get to a computer

**Comment by m1guelpf** [comment]
@clarkeash Everything seems to be OK, but Travis is failing with a database error. Do you know what happened?

**Comment by clarkeash** [comment]
Yea use the DatabaseMigrations trait instead of DatabaseTransactions

**Comment by m1guelpf** [comment]
@clarkeash Done!

**Comment by m1guelpf** [comment]
@clarkeash Any updates on this?

**Comment by clarkeash** [comment]
I will merge this, I am away at the moment but will get to it soon.

**Pull request merged**
