### PR TITLE
Add support for Laravel 6.0

### PR DESCRIPTION
**Pull request by mikemand**
_Don't mind me trying to sneak a docblock into the package..._ 😛

### CODE REVIEW

**Comment by clarkeash** [comment]
Adding support for 6 is not as simple as this. I am working on it now, thanks though 😄

**Comment by mikemand** [comment]
Hi @clarkeash,

What else did I miss? As far as I know, you aren't overriding anything from the upgrade guide, and I did a search for the `str_*` helpers and didn't find any used.

I'm just wondering what I missed so I don't make the same mistake again. Thanks!

**Comment by clarkeash** [comment]
- PHP minimum to 7.2 (because of laravel 6)
- Orchestra Testbench needs upgrading to 4.0
- PHPunit needs upgrading to 8.0 (because of testbench)
- PHPunit deprecations from 8.0 to deal with
- Carbon upgrade caused test failures.

Because of this if you did a composer install locally you would have gotten laravel 5.8 anyway.

I am almost finished.

**Comment by mikemand** [comment]
Ah, I see. Thank you for explaining. 👍

**Comment by clarkeash** [comment]
@mikemand I have pushed to master, any chance you could give it a try before I tag v4?

**Comment by mikemand** [comment]
Unfortunately, my one project that is "ready" for Laravel 6 still has several packages waiting for Laravel 6 support. I tried to remove the ones I was waiting on, but it was like fighting a hydra.

I will spin up a blank Laravel 6 project to test with.

**Comment by mikemand** [comment]
It works for me. I can generate and redeem, and all the expected Exceptions get thrown if I try to redeem too many times or for the wrong user.

**Comment by clarkeash** [comment]
Great, Thanks for your help

**Comment by mikemand** [comment]
You're welcome. 👍

**Comment by clarkeash** [comment]
v4 is tagged!

**Pull request closed without merging**
