### PR TITLE
Allow a custom model to be used

### PR DESCRIPTION
**Pull request by mikemand**
I am currently developing a multi-tenant app, so I need to add a relationship to the Invite model to connect an invite to a specific tenant.

This was highly inspired by the way Spatie allows a custom model for (most of) their packages.

### CODE REVIEW

**Comment by clarkeash** [comment]
Okay this is clearly wanted as it has been brought up before in #33 
I will take a look the weekend.

**Comment by mikemand** [comment]
Hi @clarkeash,

I didn't even see that PR, LOL. I like the additional config option to skip migrations. If you want me to implement that, I can, but I don't think it is strictly necessary because you already have a config option for the table name. As long as the migration filename and class name stay the same after you publish the migration, Laravel will use the published one instead of the one from here.

Another option is to change the migration into a `.stub` file, and check if the migration class exists like Spatie does: https://github.com/spatie/laravel-medialibrary/blob/6e3b6933592ea92642d50ae44f513292e5899cf6/src/MediaLibraryServiceProvider.php#L21-L25

**Comment by clarkeash** [comment]
I made some changes after the merge but this has gone into v3.
I am not decided on the skipping migrations, but that can always come later.

Thanks for this 😄

**Comment by mikemand** [comment]
Seems to be working great! 😃

**Pull request merged**
